spring.datasource.url=jdbc:postgresql://localhost:5432/aicodereview
spring.datasource.username=postgres
spring.datasource.password=balaji123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
gemini.api.key=AQ.${GCP_API_KEY}
github.api.url=https://api.github.com
github.token=${GITHUB_TOKEN}
gemini.model=gemini-3.5-flash-lite
